WITH RENTED AS(
SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)


SELECT DISTINCT(C.CAR_ID),
IFNULL(RENTED.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT JOIN RENTED ON C.CAR_ID = RENTED.CAR_ID
ORDER BY C.CAR_ID DESC;

